spring:
  profiles:
    active: "prod"
    # DEV clean start and schema creation
    # PROD to remember state between runs (only validate DB)

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    database: oracle
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

  datasource:
    url: ${ORA_URL}
    username: ${ORA_USER}
    password: ${ORA_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
    platform: org.hibernate.dialect.Oracle10gDialect
    hikari:
      login-timeout: 15000
      connection-timeout: 15000
      initialization-fail-timeout: 15000

server:
  port: 8080

lastfm:
  key: ${LASTFM_KEY}

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error

---

spring:
  profiles: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  thymeleaf:
    cache: false

---

spring:
  profiles: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

---

spring:
  profiles: test

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:test
    username:
    password:
    driver-class-name: org.h2.Driver

security:
  basic:
    enalbed: false
